package main

import (
	"crypto/tls"
	"fmt"
	"strings"

	"github.com/emersion/go-imap/v2"
	"github.com/emersion/go-imap/v2/imapclient"
)

// DestClient wraps an IMAP client connected to the local Dovecot server.
type DestClient struct {
	c *imapclient.Client
}

// newDestClient wraps an existing IMAP client as a DestClient.
// Used in tests to inject an already-dialled connection.
func newDestClient(c *imapclient.Client) *DestClient {
	return &DestClient{c: c}
}

// DialDest connects to the destination IMAP server over TLS and authenticates.
// If skipTLSVerify is true, certificate verification is skipped (required for
// the self-signed cert generated by scripts/gen-certs.sh).
func DialDest(host, user, pass string, skipTLSVerify bool) (*DestClient, error) {
	opts := &imapclient.Options{}
	if skipTLSVerify {
		opts.TLSConfig = &tls.Config{InsecureSkipVerify: true} // #nosec G402 -- opt-in via --skip-tls-verify for self-signed dev certs
	}
	c, err := imapclient.DialTLS(host, opts)
	if err != nil {
		return nil, fmt.Errorf("dial dest %s: %w", host, err)
	}
	if err := c.Login(user, pass).Wait(); err != nil {
		_ = c.Close()
		return nil, fmt.Errorf("login to dest: %w", err)
	}
	return newDestClient(c), nil
}

// Close closes the underlying IMAP connection.
func (d *DestClient) Close() error {
	return d.c.Close()
}

// defaultDelimiter is used when the destination server does not report a
// hierarchy delimiter via LIST.
const defaultDelimiter = '/'

// Delimiter returns the destination server's mailbox hierarchy delimiter,
// queried via an empty-mailbox-name LIST per RFC 3501 §6.3.8. Falls back to
// defaultDelimiter if the server reports none.
func (d *DestClient) Delimiter() (rune, error) {
	items, err := d.c.List("", "", nil).Collect()
	if err != nil {
		return 0, fmt.Errorf("LIST delimiter: %w", err)
	}
	if len(items) == 0 || items[0].Delim == 0 {
		return defaultDelimiter, nil
	}
	return items[0].Delim, nil
}

// translateMailboxName rewrites a mailbox name's hierarchy delimiter from
// srcDelim to dstDelim. It is a no-op if either delimiter is unknown (0) or
// they are already identical. Casing and spacing are never altered.
func translateMailboxName(name string, srcDelim, dstDelim rune) string {
	if srcDelim == 0 || dstDelim == 0 || srcDelim == dstDelim {
		return name
	}
	return strings.ReplaceAll(name, string(srcDelim), string(dstDelim))
}

// EnsureFolder ensures mailbox exists on the destination, creating it if
// needed. It does not fail if the mailbox already exists.
func (d *DestClient) EnsureFolder(mailbox string) error {
	// Try SELECT first — cheapest existence check.
	_, err := d.c.Select(mailbox, &imap.SelectOptions{ReadOnly: true}).Wait()
	if err == nil {
		return nil
	}
	// If SELECT failed the mailbox likely doesn't exist; try CREATE.
	// Ignore "already exists" errors from servers that return an error on
	// CREATE for existing mailboxes.
	if cerr := d.c.Create(mailbox, nil).Wait(); cerr != nil {
		if !isAlreadyExists(cerr) {
			return fmt.Errorf("CREATE %q: %w", mailbox, cerr)
		}
	}
	return nil
}

// Append delivers one message to mailbox on the destination server.
// Original flags and internal date are preserved.
func (d *DestClient) Append(mailbox string, msg *FullMessage) error {
	opts := &imap.AppendOptions{
		Flags: sanitizeFlags(msg.Flags),
		Time:  msg.InternalDate,
	}
	appendCmd := d.c.Append(mailbox, int64(len(msg.RFC822)), opts)
	if _, err := appendCmd.Write(msg.RFC822); err != nil {
		return fmt.Errorf("APPEND write to %q: %w", mailbox, err)
	}
	// Close signals end-of-message to the server; must be called before Wait.
	if err := appendCmd.Close(); err != nil {
		return fmt.Errorf("APPEND close for %q: %w", mailbox, err)
	}
	if _, err := appendCmd.Wait(); err != nil {
		return fmt.Errorf("APPEND wait for %q: %w", mailbox, err)
	}
	return nil
}

// flagRecent is the server-owned \Recent flag. go-imap v2 beta.8 does not
// export a constant for it because a client may never set it.
const flagRecent imap.Flag = "\\Recent"

// sanitizeFlags drops flags a client is not permitted to set via APPEND.
// \Recent is maintained solely by the server (RFC 3501 §2.3.2) and \* is the
// permanent-flags wildcard; sending either makes strict servers such as
// Dovecot reject the whole APPEND with "Invalid system flag".
func sanitizeFlags(flags []imap.Flag) []imap.Flag {
	if len(flags) == 0 {
		return nil
	}
	out := make([]imap.Flag, 0, len(flags))
	for _, f := range flags {
		switch strings.ToLower(string(f)) {
		case strings.ToLower(string(flagRecent)), strings.ToLower(string(imap.FlagWildcard)):
			continue
		}
		out = append(out, f)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// isAlreadyExists reports whether an IMAP error indicates the mailbox already
// exists (various servers phrase this differently).
func isAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "already exists") ||
		strings.Contains(msg, "mailbox exists") ||
		strings.Contains(msg, "alreadyexists")
}
